name: microfinance-platform
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
    deploy_on_push: true
  build_command: npm run build
  run_command: npm run preview
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: VITE_SUPABASE_URL
    value: https://woqesvsopdgoikpatzxp.supabase.co
  - key: VITE_SUPABASE_ANON_KEY
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvcWVzdnNvcGRnb2lrcGF0enhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjQ0NDMsImV4cCI6MjA2NzEwMDQ0M30.rIFhs-PZ24UZBOzE4nx1Ev8Pyp__7rMt5N-7kWNUeDI
  - key: PORT
    value: "8080"

domains:
- domain: yourdomain.com
  type: PRIMARY
  wildcard: true

alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED

databases: []