name: Deploy to DigitalOcean

on:
  push:
    branches: [ dev_branch, main ]
  pull_request:
    branches: [ dev_branch, main ]

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_NAME: ${{ secrets.DIGITALOCEAN_REGISTRY }}/loanspur-nexus-finance

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Deploy to DigitalOcean App Platform
      run: |
        # Get the app ID
        APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep "microfinance-platform" | awk '{print $1}')
        
        if [ -z "$APP_ID" ]; then
          echo "App not found. Creating new app..."
          doctl apps create --spec .do/app.yaml --wait
        else
          echo "Updating existing app: $APP_ID"
          doctl apps update $APP_ID --spec .do/app.yaml --wait
        fi

    - name: Check deployment status
      run: |
        APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | grep "microfinance-platform" | awk '{print $1}')
        if [ ! -z "$APP_ID" ]; then
          echo "Checking deployment status..."
          doctl apps get $APP_ID --format Spec.Services[0].SourceCommit.Hash,Spec.Services[0].SourceCommit.URL
        fi

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful!"
          echo "🌐 Your app is available at: https://loanspur.online"
        else
          echo "❌ Deployment failed!"
          exit 1
        fi